### PR TITLE
Intraframe support for VP8 and MKV

### PR DESCRIPTION
**Pull request by kecskemeti**

### CODE REVIEW

**Comment by kecskemeti** [comment]
This is just a very basic intraframe setup allowing to build on it later on. Now it supports repeated frames only as intraframes.

**Review by jcodec — CHANGES_REQUESTED** [review]
Thank you for the CL, could you format the code using java conventions preset (using 4 leading spaces and 120 char line width)? Thank you.

**Review by jcodec — CHANGES_REQUESTED** [review]
Thank you for the CL, formatting with java conventions would be great!

**Comment by kecskemeti** [comment]
I am using eclipse to edit the project, but the built in java conventions formatter changes almost every line even if I apply it on the original code. Any recommendations on a formatter that I can import to eclipse and that also produces a mostly unchanged output? Or are you ok with the format emitted by eclipse (and, as a result, an even larger changeset on the files that I have touched)?

**Comment by kecskemeti** [comment]
I have done a commit which does fix the formatting as per eclipse. If needed I can apply some other as per your recommendation.

**Pull request merged**
