### PR TITLE
bugfix: FrameGrab I-frame only 

### PR DESCRIPTION
**Pull request by zhuker**
if there’s no sync samples atom - assume all frames are i-frames

### CODE REVIEW

**Comment by zhuker** [comment]
@svitvitskiy @jcodec do you want to merge this one into master?

**Comment by zhuker** [comment]
@svitvitskiy - ideas?

**Comment by jcodec** [comment]
All the commits have been merged into master.

I cherry picked. Didn't want to pull the versions.

Stan

**Comment by zhuker** [comment]
thanks
closing

**Pull request closed without merging**
