### PR TITLE
Libvpx vp8 encoder ported to java and merged into jcodec's already existing codebase

### PR DESCRIPTION
**Pull request by kecskemeti**

### CODE REVIEW

**Comment by jcodec** [comment]
Wow! Amazing job. Thanks. It looks like there are some conflicts, could you rebase on top of HEAD and I'll be happy to merge.

**Comment by kecskemeti** [comment]
How about now? I think I have rebased it correctly.

**Comment by zhuker** [comment]
@kecskemeti this is mindblowing 
wow
what did you use for code formatting?
i've been thinking of enforcing code style for a while

**Comment by kecskemeti** [comment]
I have only used the default java conventions formatter of eclipse 2021.06. I have added minor changes that follow the guideance  recommended to me in pull request #462. The only changes I have added to the default java conventions formatter was "using 4 leading spaces and 120 char line width" as per the previous pull request. For your convenience, I have attached the formatter's configuration to this comment.
[javaconventions.zip](https://github.com/jcodec/jcodec/files/7156182/javaconventions.zip)

**Pull request merged**
