### PR TITLE
[mp4] MP4 container doesn't know the color space

### PR DESCRIPTION
**Pull request by svitvitskiy**
So it reports a dummy value of YUV420p which is incorrect for ProRes. Setting null (because we don't know) and figuring out from the actual coded picture.

### CODE REVIEW

**Comment by zhuker** [comment]
@svitvitskiy maybe we should parse avcc video sample entry sps (if available) for that? 
like here https://ffmpeg.org/pipermail/ffmpeg-cvslog/2013-January/058857.html

**Comment by svitvitskiy** [comment]
This will require pulling the first frame. We'll have to cache it and later feed it through the 'nextFrame' (possible but complicated). Then we can ask the specific decoder to probe it's frame for the metadata (all the supported decoders support this).

Let me know if you want to do that.

I'd say color information is specific to the codec not the container, the color is known the moment the first image is decoded. All the decoders support probing the packet for metadata.

**Comment by zhuker** [comment]
i mean `stsd.avcc.sps`

**Comment by svitvitskiy** [comment]
Sure, agree.

**Pull request merged**
